    set_location_assignment PIN_AA11 -to n_Reset_0
    set_location_assignment PIN_U9 -to die2_Segment_A
    set_location_assignment PIN_W8 -to die2_Segment_B
    set_location_assignment PIN_V8 -to die2_Segment_C
    set_location_assignment PIN_Y4 -to die2_Segment_D
    set_location_assignment PIN_T11 -to die2_Segment_E
    set_location_assignment PIN_R11 -to die2_Segment_F
    set_location_assignment PIN_T10 -to die2_Segment_G
    set_location_assignment PIN_W7 -to die2_DecimalPoint
    set_location_assignment PIN_B11 -to n_Block_die_4_0
    set_location_assignment PIN_U11 -to die1_Segment_A
    set_location_assignment PIN_G18 -to die1_Segment_B
    set_location_assignment PIN_M8 -to die1_Segment_C
    set_location_assignment PIN_L6 -to die1_Segment_D
    set_location_assignment PIN_W10 -to die1_Segment_E
    set_location_assignment PIN_U10 -to die1_Segment_F
    set_location_assignment PIN_V9 -to die1_Segment_G
    set_location_assignment PIN_L7 -to die1_DecimalPoint
    set_location_assignment PIN_T3 -to die4_Segment_A
    set_location_assignment PIN_R6 -to die4_Segment_B
    set_location_assignment PIN_R5 -to die4_Segment_C
    set_location_assignment PIN_P7 -to die4_Segment_D
    set_location_assignment PIN_N8 -to die4_Segment_E
    set_location_assignment PIN_N7 -to die4_Segment_F
    set_location_assignment PIN_P8 -to die4_Segment_G
    set_location_assignment PIN_P6 -to die4_DecimalPoint
    set_location_assignment PIN_B12 -to n_Block_die_2_0
    set_location_assignment PIN_R10 -to die3_Segment_A
    set_location_assignment PIN_T9 -to die3_Segment_B
    set_location_assignment PIN_R9 -to die3_Segment_C
    set_location_assignment PIN_R8 -to die3_Segment_D
    set_location_assignment PIN_T7 -to die3_Segment_E
    set_location_assignment PIN_R7 -to die3_Segment_F
    set_location_assignment PIN_T4 -to die3_Segment_G
    set_location_assignment PIN_T8 -to die3_DecimalPoint
    set_location_assignment PIN_A11 -to n_Block_die_3_0
    set_location_assignment PIN_A12 -to n_Block_die_1_0
    set_location_assignment PIN_G22 -to n_Mode_0
    set_location_assignment PIN_T22 -to Clock_0
    set_location_assignment PIN_B4 -to L1_0
    set_location_assignment PIN_B8 -to L2_0
    set_location_assignment PIN_B14 -to L3_0
    set_location_assignment PIN_B18 -to L4_0
    set_location_assignment PIN_C22 -to L5_0
    set_location_assignment PIN_H22 -to L6_0
